### ISSUE TITLE
Js Complier (1.14.9.2 ) not working in lastest Visual Studio(17.4.2)!

### ISSUE THREAD

**Issue by mucahitbugday** [failwyn/WebCompiler#63]
Hello,

I'm  update on Js Complier, not working complier on Real time!
Compiling in version 2.

my files like this
![image](https://user-images.githubusercontent.com/65226295/205276876-4f35994e-d90f-431c-a892-8266b77bedf3.png)

**Comment by failwyn** [comment]
Is it giving you an error message? Would you be able to provide a sample application that I can test? I tested a few js issues before release and they all worked as expected.

**Comment by mucahitbugday** [comment]
I just tried to create a new project in the project. not working in my old project.
Could the problem be in my project?
the project is a group project, the other group members have version 1.14.8 installed and there is no problem with them.

**Comment by failwyn** [comment]
Without an error message, reproduction steps, or a sample project to test, it's going to be very difficult to identify the issue; Can you provide any more details on what is happening?

**Comment by szalapski** [comment]
I'm getting the following:

Severity	Code	Description	Project	File	Line	Suppression State
Error		node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\g520844\AppData\Local\Temp\WebCompiler1.14.9.2\node_modules\sass\sass.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
	TradeCars.Client	C:\s\TradeCars\TradeCars\Client\Styles\app.scss	0

**Comment by failwyn** [comment]
Can you try uninstalling and reinstalling the extension, It looks like it couldn’t extract the node modules; possibly a permission issue?

**Comment by szalapski** [comment]
I tried that, didn't help.  Thanks for the idea.

**Comment by failwyn** [comment]
Can you zip the C:\Users\myself\AppData\Local\Temp\WebCompiler1.14.9.2\node_modules\ directory and send it to me?

**Comment by szalapski** [comment]
[Uploading node_modules.zip…](Here you go).

**Comment by failwyn** [comment]
Your node_modules folder has all of the directories, but none of the files, there has to be something on your machine preventing the 7z file from being extracted properly.

Can you this? 

1. Uninstall the WebCompiler extension
2. Close Visual Studio
3. Clear your Temp Files (specifically delete the C:\Users\myself\AppData\Local\Temp\WebCompiler1.14.9.2 directory)
4. Open Visual Studio
5. Install the Extension
6. Check the node_modules folderfor the node_modules\sass\sass.js file at  C:\Users\myself\AppData\Local\Temp\WebCompiler1.14.9.2

**Comment by szalapski** [comment]
log.txt has just "Friday, December 2, 2022"

**Comment by failwyn** [comment]
You can probably simplify this by just deleting that folder and restarting visual studio.

I didn't change anything with the extraction process, so I'm really curious to find out what caused this for you; it appears like the extraction was aborted for some reason and afterwards, it saw the that the directory was there and skipped the extraction; I'll do some testing to see if there's an efficient way to verify that directory when the extension initializes.

**Comment by failwyn** [comment]
Try just deleting the node_modules folder first.

**Comment by cklenk** [comment]
I was getting babel.cmd is not recognized as an internal or external command, operable program or batch file errors. I deleted the WebCompiler temp folders and then was able to recompile all my js and scss. I was on VS 2022 17.4.3 Win 11 22H2.

**Comment by szalapski** [comment]
> Try just deleting the node_modules folder first.

That worked.

**Comment by failwyn** [comment]
I wonder if this had something to do with modifying the revision number instead of incrementing the build version? Next release I’ll go back to keeping the revision 0 to see if that helps; I’m just waiting for a new release of NUglify to fix the ‘none’ optimization.

**Comment by failwyn** [comment]
@szalapski @cklenk @mucahitbugday Let me know if this issue occurs when upgrading to 1.14.10

**Comment by szalapski** [comment]
It worked no problem.

**Comment by failwyn** [comment]
Interesting; I wonder if this was connected to having the revision number?

**Comment by paradoxall** [comment]
I had this :

Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\Users\egagnon\AppData\Local\Temp\WebCompiler1.14.10\node_modules\sass\sass.dart.js:1



SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\egagnon\AppData\Local\Temp\WebCompiler1.14.10\node_modules\sass\sass.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
	WMS-Octopus-V2	C:\Users\egagnon\source\repos\b1wms\WMS-Octopus-V2\WMS-Octopus-V2\Shared\WmsTextTable.razor.scss	0	

and [szalapski](https://github.com/szalapski) instruction fix my issue thanx man !!
https://github.com/failwyn/WebCompiler/issues/63#issuecomment-1337869562
